#nullable enable
// =============================================================================
// Author: Vladyslav Zaiets | https://sarmkadan.com
// CTO & Software Architect
// =============================================================================

namespace DotnetAuthServer.Tests;

using DotnetAuthServer.Domain.Entities;
using FluentAssertions;
using Xunit;

/// <summary>
/// Tests for WebAuthnCredential domain entity.
/// </summary>
public sealed class WebAuthnCredentialTests
{
    private static WebAuthnCredential CreateValidCredential()
    {
        return new WebAuthnCredential
        {
            CredentialId = "AQIDBAUG", // Base64URL encoded "01234567"
            PublicKey = [0x04, 0x90, 0x12, 0x34, 0x56, 0x78, 0x90, 0xAB], // Sample public key bytes
            Algorithm = -7, // ES256
            SignatureCounter = 123,
            UserId = "user-123",
            FriendlyName = "YubiKey 5C Nano",
            AaGuid = "adce0002-35bc-c60a-648b-0b25f1f05503",
            BackupEligible = true,
            BackedUp = true
        };
    }

    // -------------------------------------------------------------------------
    // Property initialization tests
    // -------------------------------------------------------------------------

    [Fact]
    public void Constructor_InitializesProperties_WithDefaultValues()
    {
        // Arrange & Act
        var credential = new WebAuthnCredential();

        // Assert
        credential.Id.Should().NotBeNullOrEmpty("Id should be auto-generated as GUID string");
        credential.CredentialId.Should().BeEmpty("CredentialId should default to empty string");
        credential.PublicKey.Should().BeEmpty("PublicKey should default to empty byte array");
        credential.Algorithm.Should().Be(0, "Algorithm should default to 0");
        credential.SignatureCounter.Should().Be(0, "SignatureCounter should default to 0");
        credential.UserId.Should().BeEmpty("UserId should default to empty string");
        credential.FriendlyName.Should().BeEmpty("FriendlyName should default to empty string");
        credential.AaGuid.Should().BeEmpty("AaGuid should default to empty string");
        credential.BackupEligible.Should().BeFalse("BackupEligible should default to false");
        credential.BackedUp.Should().BeFalse("BackedUp should default to false");
        credential.CreatedAt.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(5));
        credential.IsActive.Should().BeTrue("IsActive should default to true");
    }

    [Fact]
    public void Constructor_InitializesProperties_WithCustomValues()
    {
        // Arrange
        var credentialId = "test-credential-id";
        var publicKey = new byte[] { 0x01, 0x02, 0x03, 0x04 };
        var userId = "test-user";
        var friendlyName = "Test Device";
        var aaGuid = "12345678-1234-5678-1234-567812345678";

        // Act
        var credential = new WebAuthnCredential
        {
            CredentialId = credentialId,
            PublicKey = publicKey,
            Algorithm = -257, // RS256
            SignatureCounter = 42,
            UserId = userId,
            FriendlyName = friendlyName,
            AaGuid = aaGuid,
            BackupEligible = true,
            BackedUp = false,
            IsActive = false
        };

        // Assert
        credential.CredentialId.Should().Be(credentialId);
        credential.PublicKey.Should().BeEquivalentTo(publicKey);
        credential.Algorithm.Should().Be(-257);
        credential.SignatureCounter.Should().Be(42);
        credential.UserId.Should().Be(userId);
        credential.FriendlyName.Should().Be(friendlyName);
        credential.AaGuid.Should().Be(aaGuid);
        credential.BackupEligible.Should().BeTrue();
        credential.BackedUp.Should().BeFalse();
        credential.IsActive.Should().BeFalse();
    }

    // -------------------------------------------------------------------------
    // Property value tests
    // -------------------------------------------------------------------------

    [Fact]
    public void Id_IsAutoGeneratedGuidString()
    {
        // Arrange & Act
        var credential1 = new WebAuthnCredential();
        var credential2 = new WebAuthnCredential();

        // Assert
        credential1.Id.Should().MatchRegex(
            "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
            "Id should be a valid GUID string");
        credential2.Id.Should().NotBe(credential1.Id, "Each credential should have a unique Id");
    }

    [Fact]
    public void CredentialId_CanBeSetToValidBase64UrlString()
    {
        // Arrange
        var credential = CreateValidCredential();
        var newCredentialId = "AQIDBAUG"; // Base64URL encoded "01234567"

        // Act
        credential.CredentialId = newCredentialId;

        // Assert
        credential.CredentialId.Should().Be(newCredentialId);
    }

    [Fact]
    public void CredentialId_CanBeEmpty()
    {
        // Arrange & Act
        var credential = new WebAuthnCredential();

        // Assert
        credential.CredentialId.Should().BeEmpty();
    }

    [Fact]
    public void PublicKey_CanBeSetToValidByteArray()
    {
        // Arrange
        var credential = CreateValidCredential();
        var newPublicKey = new byte[] { 0x04, 0x90, 0x12, 0x34 };

        // Act
        credential.PublicKey = newPublicKey;

        // Assert
        credential.PublicKey.Should().BeEquivalentTo(newPublicKey);
    }

    [Fact]
    public void PublicKey_CanBeEmptyArray()
    {
        // Arrange
        var credential = CreateValidCredential();

        // Act
        credential.PublicKey = [];

        // Assert
        credential.PublicKey.Should().BeEmpty();
    }

    [Fact]
    public void Algorithm_CanBeSetToValidCoseAlgorithm()
    {
        // Arrange
        var credential = CreateValidCredential();

        // Act
        credential.Algorithm = -257; // RS256

        // Assert
        credential.Algorithm.Should().Be(-257);
    }

    [Fact]
    public void Algorithm_DefaultsToZero()
    {
        // Arrange & Act
        var credential = new WebAuthnCredential();

        // Assert
        credential.Algorithm.Should().Be(0);
    }

    [Fact]
    public void SignatureCounter_CanBeIncremented()
    {
        // Arrange
        var credential = CreateValidCredential();
        var initialValue = credential.SignatureCounter;

        // Act
        credential.SignatureCounter++;

        // Assert
        credential.SignatureCounter.Should().Be(initialValue + 1);
    }

    [Fact]
    public void SignatureCounter_CanBeSetToLargeValue()
    {
        // Arrange
        var credential = CreateValidCredential();

        // Act
        credential.SignatureCounter = uint.MaxValue;

        // Assert
        credential.SignatureCounter.Should().Be(uint.MaxValue);
    }

    [Fact]
    public void UserId_CanBeSetToValidString()
    {
        // Arrange
        var credential = CreateValidCredential();
        var newUserId = "user-456";

        // Act
        credential.UserId = newUserId;

        // Assert
        credential.UserId.Should().Be(newUserId);
    }

    [Fact]
    public void UserId_CanBeEmpty()
    {
        // Arrange
        var credential = CreateValidCredential();

        // Act
        credential.UserId = string.Empty;

        // Assert
        credential.UserId.Should().BeEmpty();
    }

    [Fact]
    public void FriendlyName_CanBeSetToValidString()
    {
        // Arrange
        var credential = CreateValidCredential();
        var newFriendlyName = "Windows Hello on Surface Pro";

        // Act
        credential.FriendlyName = newFriendlyName;

        // Assert
        credential.FriendlyName.Should().Be(newFriendlyName);
    }

    [Fact]
    public void FriendlyName_CanBeEmpty()
    {
        // Arrange
        var credential = CreateValidCredential();

        // Act
        credential.FriendlyName = string.Empty;

        // Assert
        credential.FriendlyName.Should().BeEmpty();
    }

    [Fact]
    public void AaGuid_CanBeSetToValidGuidString()
    {
        // Arrange
        var credential = CreateValidCredential();
        var newAaGuid = "adce0002-35bc-c60a-648b-0b25f1f05503";

        // Act
        credential.AaGuid = newAaGuid;

        // Assert
        credential.AaGuid.Should().Be(newAaGuid);
    }

    [Fact]
    public void AaGuid_CanBeEmpty()
    {
        // Arrange
        var credential = CreateValidCredential();

        // Act
        credential.AaGuid = string.Empty;

        // Assert
        credential.AaGuid.Should().BeEmpty();
    }

    [Fact]
    public void BackupEligible_CanBeSetToTrue()
    {
        // Arrange
        var credential = CreateValidCredential();

        // Act
        credential.BackupEligible = true;

        // Assert
        credential.BackupEligible.Should().BeTrue();
    }

    [Fact]
    public void BackupEligible_CanBeSetToFalse()
    {
        // Arrange
        var credential = CreateValidCredential();

        // Act
        credential.BackupEligible = false;

        // Assert
        credential.BackupEligible.Should().BeFalse();
    }

    [Fact]
    public void BackedUp_CanBeSetToTrue()
    {
        // Arrange
        var credential = CreateValidCredential();

        // Act
        credential.BackedUp = true;

        // Assert
        credential.BackedUp.Should().BeTrue();
    }

    [Fact]
    public void BackedUp_CanBeSetToFalse()
    {
        // Arrange
        var credential = CreateValidCredential();

        // Act
        credential.BackedUp = false;

        // Assert
        credential.BackedUp.Should().BeFalse();
    }

    [Fact]
    public void IsActive_CanBeSetToTrue()
    {
        // Arrange
        var credential = new WebAuthnCredential { IsActive = false };

        // Act
        credential.IsActive = true;

        // Assert
        credential.IsActive.Should().BeTrue();
    }

    [Fact]
    public void IsActive_CanBeSetToFalse()
    {
        // Arrange
        var credential = CreateValidCredential();

        // Act
        credential.IsActive = false;

        // Assert
        credential.IsActive.Should().BeFalse();
    }

    [Fact]
    public void CreatedAt_IsSetToUtcNowByDefault()
    {
        // Arrange & Act
        var credential = new WebAuthnCredential();

        // Assert
        credential.CreatedAt.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(5));
    }

    [Fact]
    public void LastUsedAt_IsNullByDefault()
    {
        // Arrange & Act
        var credential = new WebAuthnCredential();

        // Assert
        credential.LastUsedAt.Should().BeNull();
    }

    // -------------------------------------------------------------------------
    // Edge cases and boundary values
    // -------------------------------------------------------------------------

    [Fact]
    public void PublicKey_HandlesLargeByteArray()
    {
        // Arrange
        var credential = CreateValidCredential();
        var largeKey = new byte[1024];
        for (int i = 0; i < largeKey.Length; i++)
        {
            largeKey[i] = (byte)(i % 256);
        }

        // Act
        credential.PublicKey = largeKey;

        // Assert
        credential.PublicKey.Should().BeEquivalentTo(largeKey);
        credential.PublicKey.Should().HaveCount(1024);
    }

    [Fact]
    public void FriendlyName_HandlesLongString()
    {
        // Arrange
        var credential = CreateValidCredential();
        var longName = new string('A', 500);

        // Act
        credential.FriendlyName = longName;

        // Assert
        credential.FriendlyName.Should().Be(longName);
        credential.FriendlyName.Should().HaveLength(500);
    }

    [Fact]
    public void AaGuid_HandlesValidGuidFormat()
    {
        // Arrange
        var credential = CreateValidCredential();
        var validGuid = Guid.NewGuid().ToString();

        // Act
        credential.AaGuid = validGuid;

        // Assert
        credential.AaGuid.Should().Be(validGuid);
    }

    [Fact]
    public void SignatureCounter_HandlesZero()
    {
        // Arrange
        var credential = CreateValidCredential();

        // Act
        credential.SignatureCounter = 0;

        // Assert
        credential.SignatureCounter.Should().Be(0);
    }

    // -------------------------------------------------------------------------
    // Object behavior tests
    // -------------------------------------------------------------------------

    [Fact]
    public void ToString_DoesNotThrow()
    {
        // Arrange
        var credential = CreateValidCredential();

        // Act
        Action act = () => _ = credential.ToString();

        // Assert
        act.Should().NotThrow();
    }

    [Fact]
    public void Equals_WithSameId_ReturnsTrue()
    {
        // Arrange
        var credential1 = new WebAuthnCredential { Id = "test-id" };
        var credential2 = new WebAuthnCredential { Id = "test-id" };

        // Act
        var areEqual = credential1.Equals(credential2);

        // Assert - WebAuthnCredential uses reference equality by default
        // This test documents the actual behavior
        areEqual.Should().BeFalse("WebAuthnCredential uses reference equality");
    }

    [Fact]
    public void Equals_WithSameReference_ReturnsTrue()
    {
        // Arrange
        var credential = new WebAuthnCredential { Id = "test-id" };

        // Act
        var areEqual = credential.Equals(credential);

        // Assert
        areEqual.Should().BeTrue("an object should equal itself");
    }

    [Fact]
    public void GetHashCode_ReturnsConsistentValue()
    {
        // Arrange
        var credential = CreateValidCredential();
        var hashCode1 = credential.GetHashCode();

        // Act
        var hashCode2 = credential.GetHashCode();

        // Assert
        hashCode1.Should().Be(hashCode2);
    }
}