#nullable enable
// =============================================================================
// Author: Vladyslav Zaiets | https://sarmkadan.com
// CTO & Software Architect
// =============================================================================

namespace DotnetAuthServer.Controllers;

using Microsoft.AspNetCore.Mvc;
using DotnetAuthServer.Configuration;
using DotnetAuthServer.Data.Repositories;
using DotnetAuthServer.Domain.Models;
using DotnetAuthServer.Exceptions;
using DotnetAuthServer.Services;

/// <summary>
/// REST API for TOTP multi-factor authentication management.
/// Provides endpoints for enrolling, confirming, verifying and disabling MFA.
/// All routes are nested under <c>/api/users/{userId}/mfa</c>.
/// </summary>
[ApiController]
[Route("api/users/{userId}/mfa")]
[Produces("application/json")]
public sealed class MfaController : ControllerBase
{
    private readonly TotpService _totpService;
    private readonly IUserRepository? _userRepository;
    private readonly ILogger<MfaController> _logger;

    /// <summary>
    /// Initializes a new instance of <see cref="MfaController"/>.
    /// </summary>
    public MfaController(
        TotpService totpService,
        ILogger<MfaController> logger,
        Data.Repositories.IUserRepository? userRepository = null)
    {
        _totpService = totpService;
        _logger = logger;
        _userRepository = userRepository;
    }

    // -------------------------------------------------------------------------
    // Status
    // -------------------------------------------------------------------------

    /// <summary>
    /// Returns the current MFA status for the specified user.
    /// </summary>
    /// <param name="userId">Target user ID.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    [HttpGet]
    [ProducesResponseType(typeof(ApiResponse<MfaStatusResponse>), 200)]
    public async Task<IActionResult> GetStatusAsync(string userId, CancellationToken cancellationToken)
    {
        try
        {
            var status = await _totpService.GetStatusAsync(userId, cancellationToken);
            return Ok(ApiResponse<MfaStatusResponse>.SuccessResponse(status));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting MFA status for user {UserId}", userId);
            return StatusCode(500, ApiResponse.ErrorResponse(Constants.ErrorCodes.ServerError, ex.Message));
        }
    }

    // -------------------------------------------------------------------------
    // Setup
    // -------------------------------------------------------------------------

    /// <summary>
    /// Initiates TOTP enrollment. Returns a secret key, QR-code-ready provisioning URI,
    /// and backup codes. The user must call <c>POST /confirm</c> with a valid TOTP code
    /// before MFA is activated.
    /// </summary>
    /// <param name="userId">Target user ID.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    [HttpPost("setup")]
    [ProducesResponseType(typeof(ApiResponse<MfaSetupResponse>), 200)]
    [ProducesResponseType(404)]
    public async Task<IActionResult> SetupAsync(string userId, CancellationToken cancellationToken)
    {
        try
        {
            var user = _userRepository is null
                ? null
                : await _userRepository.GetByIdAsync(userId, cancellationToken);

            if (_userRepository is not null && user is null)
                return NotFound(ApiResponse.ErrorResponse("user_not_found", $"User '{userId}' not found"));

            var username = user?.Username ?? userId;
            var setup = await _totpService.InitiateSetupAsync(userId, username, cancellationToken);
            return Ok(ApiResponse<MfaSetupResponse>.SuccessResponse(setup,
                "Scan the QR code or enter the secret key in your authenticator app, then confirm with POST /confirm"));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error setting up MFA for user {UserId}", userId);
            return StatusCode(500, ApiResponse.ErrorResponse(Constants.ErrorCodes.ServerError, ex.Message));
        }
    }

    /// <summary>
    /// Confirms TOTP setup by verifying the first code generated by the authenticator app.
    /// MFA is enabled only after this step succeeds.
    /// </summary>
    /// <param name="userId">Target user ID.</param>
    /// <param name="request">Contains the 6-digit TOTP code.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    [HttpPost("confirm")]
    [Consumes("application/json")]
    [ProducesResponseType(200)]
    [ProducesResponseType(400)]
    [ProducesResponseType(404)]
    public async Task<IActionResult> ConfirmSetupAsync(
        string userId,
        [FromBody] MfaVerifyRequest request,
        CancellationToken cancellationToken)
    {
        if (!ModelState.IsValid)
            return BadRequest(ModelState);

        try
        {
            await _totpService.ConfirmSetupAsync(userId, request.Code, cancellationToken);
            return Ok(ApiResponse.SuccessResponse("MFA has been enabled for your account"));
        }
        catch (AuthServerException ex)
        {
            return StatusCode(ex.StatusCode, ApiResponse.ErrorResponse(ex.ErrorCode, ex.Message));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error confirming MFA setup for user {UserId}", userId);
            return StatusCode(500, ApiResponse.ErrorResponse(Constants.ErrorCodes.ServerError, ex.Message));
        }
    }

    // -------------------------------------------------------------------------
    // Verification
    // -------------------------------------------------------------------------

    /// <summary>
    /// Verifies a TOTP or backup code for an already-enrolled user.
    /// Returns 200 on success, 401 on failure.
    /// </summary>
    /// <param name="userId">Target user ID.</param>
    /// <param name="request">Contains the 6-digit TOTP code or an 8-character backup code.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    [HttpPost("verify")]
    [Consumes("application/json")]
    [ProducesResponseType(200)]
    [ProducesResponseType(401)]
    public async Task<IActionResult> VerifyAsync(
        string userId,
        [FromBody] MfaVerifyRequest request,
        CancellationToken cancellationToken)
    {
        if (!ModelState.IsValid)
            return BadRequest(ModelState);

        try
        {
            var valid = await _totpService.VerifyAsync(userId, request.Code, cancellationToken);
            if (!valid)
            {
                return Unauthorized(ApiResponse.ErrorResponse(
                    Constants.ErrorCodes.InvalidGrant,
                    "Invalid or expired MFA code"));
            }

            return Ok(ApiResponse.SuccessResponse("MFA verification successful"));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error verifying MFA for user {UserId}", userId);
            return StatusCode(500, ApiResponse.ErrorResponse(Constants.ErrorCodes.ServerError, ex.Message));
        }
    }

    // -------------------------------------------------------------------------
    // Disable
    // -------------------------------------------------------------------------

    /// <summary>
    /// Disables and removes the TOTP credential for the specified user.
    /// The user will no longer be prompted for MFA on subsequent logins.
    /// </summary>
    /// <param name="userId">Target user ID.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    [HttpDelete]
    [ProducesResponseType(200)]
    public async Task<IActionResult> DisableMfaAsync(string userId, CancellationToken cancellationToken)
    {
        try
        {
            await _totpService.DisableMfaAsync(userId, cancellationToken);
            return Ok(ApiResponse.SuccessResponse($"MFA has been disabled for user '{userId}'"));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error disabling MFA for user {UserId}", userId);
            return StatusCode(500, ApiResponse.ErrorResponse(Constants.ErrorCodes.ServerError, ex.Message));
        }
    }
}
